import { CODE_COLORS } from "https://deno.land/x/json_colorize@0.1.0/mod.ts";

export const colors = {
  BRACE: CODE_COLORS.GRAY,
  BRACKET: CODE_COLORS.GRAY,
  COLON: CODE_COLORS.GRAY,
  COMMA: CODE_COLORS.GRAY,
  STRING_KEY: CODE_COLORS.BLUE,
  STRING_LITERAL: CODE_COLORS.GREEN,
  NUMBER_LITERAL: CODE_COLORS.YELLOW,
  BOOLEAN_LITERAL: CODE_COLORS.CYAN,
  NULL_LITERAL: CODE_COLORS.RED,
};
