name: CD

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: release ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.22
      - name: Compile for ${{ matrix.target }}
        run: deno compile --allow-net --allow-env --target ${{ matrix.target }} -o mvola src/main.ts
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Packaging final binary
        shell: bash
        run: |
          tar czvf mvola_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz mvola
          shasum -a 512 mvola_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz > mvola_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha512
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mvola_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz
            mvola_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha512
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}